name: PublicCrafters
main: io.github.bananapuncher714.crafters.PublicCrafters
version: 4.12.7
author: BananaPuncher714
description: Adds public workbenches to Minecraft
api-version: 1.13
commands:
    craftingtable:
        description: Toggles private crafting
permissions:
    publiccrafters.admin:
        default: op
    publiccrafters.private:
        default: true
    publiccrafters.reload:
        default: op