name: PublicCrafters
main: io.github.bananapuncher714.crafters.PublicCrafters
version: 4.0
author: BananaPuncher714
description: Adds public workbenches to Minecraft
commands:
    craftingtable:
        description: Toggles private crafting
permissions:
    publiccrafters.private:
        default: true
    publiccrafters.reload:
        default: op