name: PublicCrafters
main: io.github.bananapuncher714.crafters.PublicCraftersMain
version: 2.6
author: BananaPuncher714
description: Adds public workbenches to minecraft
commands:
    craftingtable:
        description: Toggles private crafting