name: PublicCrafters
main: io.github.bananapuncher714.crafters.PublicCrafters
version: 3.1
author: BananaPuncher714
description: Adds public workbenches to Minecraft
commands:
    craftingtable:
        description: Toggles private crafting